# OPERACIONES
AVANZAR_F = 'F'
AVANZAR_G = 'G'
AVANZAR_SIN_ESCRIBIR_F = 'f'
AVANZAR_SIN_ESCRIBIR_G = 'g'
GIRAR_DERECHA = '+'
GIRAR_IZQUIERDA = '-'
GIRAR_180 = '|'
APILAR = '['
DESAPILAR = ']'


# COLORES
BLACK = "black"
RED = "red"
GREEN = "green"
YELLOW = "yellow"
VIOLET = "violet"
BLUE = "blue"
COLORS = [BLACK, RED, GREEN, YELLOW, VIOLET, BLUE]
COLOR_INDEX = 0

# 
UNIDAD = 10
ANGULO_INICIAL = 90
GIRO_COMPLETO = 180
ITERACIONES = 6

# INDICES SYS.ARGV
INDICE_RUTA = 1
INDICE_SVG = 2